# Site settings
title: Nicolò Gozzi 
description: A space for my projects and my ideas
# baseurl: "" # the subpath of your site, e.g. /blog
url: "http://ngozzi.github.io"

# User settings
username: Nicolò Gozzi
user_description: I am a Physics student and I am passionate about latest technology innovations. During my education, I have always tried to focus my studies on interdisciplinary problems, since I strongly believe that the most fascinating issues lie in the in-between. Because of this, I am always looking for new opportunities to broaden my horizons and to meet people with different backgrounds.
user_title: Physics Student
email: nicolo@gozzi.biz
#twitter_username: lorem_ipsum
github_username:  ngozzi
#gplus_username:  lorem_ipsum

# Google-analytics
#google-analytics:
#id: ""

exclude: ['package.json', 'src' , 'node_modules']
