# Site settings
title: Nicolò Gozzi 
description: A space for my projects and my ideas
# baseurl: "" # the subpath of your site, e.g. /blog
url: "http://ngozzi.github.io"

# User settings
username: Nicolò Gozzi
user_description: I'm a physics student passionate about data analysis, machine learning and quantitative research in general!
user_title: Physics Student
email: nicolo@gozzi.biz
#twitter_username: lorem_ipsum
github_username:  ngozzi
#gplus_username:  lorem_ipsum

# Google-analytics
#google-analytics:
#id: ""

exclude: ['package.json', 'src' , 'node_modules']
